name: Docker

on:
  workflow_call:

jobs:
  docker:
    runs on: ubuntu-latest
    steps:
      - uses: actions/chekout@v6.0.3
      - name: Setup Docker Build
        uses: docker/setup-buildx-action@v4.1.0
      
      
